In [1]:
import pandas as pd
import sqlite3
import numpy as np

In [8]:
# Crypto currency database
# The database we will use contains two tables cryptocoins_cryptocurrency and cryptocoins_exchange.

# Using the given sqlite3 connection and the read_sql method write a single query that:

# Join both tables and return the list of cryptocurrencies with its exchanges. You should use the column with the exchange ID on each table to perform the join.

# As both tables have a name column you should rename cryptocoins_cryptocurrency.name as coin_name and cryptocoins_exchange.name as exchange. Also select symbol, price_usd and percent_change_7d columns.

# Store the information in a crypto_df DataFrame.

# Once you have the crypto_df DataFrame, create a new weekly_change_df with the crypto_df data sorted by percent_change_7d from highest to lowest.

In [14]:
# This note book will be using the cryptos-sql file. W need to read it and execute it

# 1. Craete an empty database to our ram

conn = sqlite3.connect(':memory:')

# 2. We open our sql file

with open(r'C:\Users\HP\Desktop\Data-Science-Foundations\Databases\cryptos.sql' , 'r') as file:
    sqlite3_script = file.read()

# We execute our sql script

conn.executescript(sqlite3_script)

# We create a 2 dfs. The sql script has many tables but we will be using 2 tables.(cryptocoins_cryptocurrency and cryptocoins_exchange)

df_crypto_currency= pd.read_sql('SELECT * FROM cryptocoins_cryptocurrency' , conn , index_col=['id'])

# 2ND DF

df_crypto_exchange = pd.read_sql("SELECT * FROM cryptocoins_exchange" , conn)

In [15]:
df_crypto_currency

,name,slug,symbol,rank,price_usd,price_btc,volume_usd_24h,market_cap_usd,available_supply,total_supply,max_supply,percent_change_1h,percent_change_24h,percent_change_7d,exchange_id,last_updated
id,,,,,,,,,,,,,,,,
1,Bitcoin,bitcoin,BTC,1,8707.37,1.000000e+00,1.874329e+10,157139896329,18046762,18046762,2.100000e+07,-0.12,-1.08,-5.91,1,2019-11-14 13:02:23.293956
2,Ethereum,ethereum,ETH,2,186.50,2.143270e-02,7.703154e+09,20244944406,108549236,108549236,NaN,-0.21,-0.33,-0.66,1,2019-11-14 13:02:23.326936
3,XRP,ripple,XRP,3,0.27,3.080000e-05,1.320452e+09,11621563439,43298481757,99991298961,1.000000e+11,-0.33,-1.83,-8.22,1,2019-11-14 13:02:23.337368
4,Bitcoin Cash,bitcoin-cash,BCH,4,278.92,3.205290e-02,1.759249e+09,5051906817,18112350,18112350,2.100000e+07,0.17,-3.00,-4.76,3,2019-11-14 13:02:23.348683
5,Tether,tether,USDT,5,1.01,1.159000e-04,2.172326e+10,4141681919,4108044456,4207771504,NaN,-0.23,0.33,0.45,1,2019-11-14 13:02:23.360212
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,iExec RLC,rlc,RLC,96,0.73,8.420000e-05,9.123598e+05,58690317,80070793,86999785,NaN,1.75,-2.65,10.64,1,2019-11-14 13:02:26.339720
97,BitMax Token,bitmax-token,BTMX,97,0.07,8.000000e-06,3.352881e+06,54953077,787683608,787683608,NaN,-0.72,0.83,1.18,4,2019-11-14 13:02:26.349654
98,Flexacoin,flexacoin,FXC,98,0.00,3.000000e-07,2.182664e+04,54053204,21223945749,21223945749,1.000000e+11,0.01,2.53,-0.39,1,2019-11-14 13:02:26.359969
99,Chiliz,chiliz,CHZ,99,0.01,1.600000e-06,1.139611e+07,53955717,3762769182,8888888888,NaN,0.84,-3.41,5.44,2,2019-11-14 13:02:26.376334
100,Ardor,ardor,ARDR,100,0.05,6.100000e-06,2.348666e+06,53205799,998999495,998999495,9.989995e+08,-0.34,-4.22,-3.56,1,2019-11-14 13:02:26.387078

In [29]:
df_crypto_currency = df_crypto_currency.rename(columns={'name' : 'coin_name'})

In [30]:
df_crypto_exchange = df_crypto_exchange.rename(columns={'name' : 'exchange'})

In [31]:
df_crypto_exchange

   id  exchange                       url
0   1  Bitstamp  https://www.bitstamp.net
1   2  Poloniex      https://poloniex.com
2   3   Binance  https://www.binance.com/
3   4      OKEx      https://www.okex.com

In [35]:
# Merge both dfs

combined_df = pd.merge(df_crypto_currency , df_crypto_exchange , left_on= 'exchange_id' , right_on= 'id' , how= 'inner')

combined_df.drop(columns = ['id'])

,coin_name,slug,symbol,rank,price_usd,price_btc,volume_usd_24h,market_cap_usd,available_supply,total_supply,max_supply,percent_change_1h,percent_change_24h,percent_change_7d,exchange_id,last_updated,exchange,url
0,Bitcoin,bitcoin,BTC,1,8707.37,1.000000e+00,1.874329e+10,157139896329,18046762,18046762,2.100000e+07,-0.12,-1.08,-5.91,1,2019-11-14 13:02:23.293956,Bitstamp,https://www.bitstamp.net
1,Ethereum,ethereum,ETH,2,186.50,2.143270e-02,7.703154e+09,20244944406,108549236,108549236,NaN,-0.21,-0.33,-0.66,1,2019-11-14 13:02:23.326936,Bitstamp,https://www.bitstamp.net
2,XRP,ripple,XRP,3,0.27,3.080000e-05,1.320452e+09,11621563439,43298481757,99991298961,1.000000e+11,-0.33,-1.83,-8.22,1,2019-11-14 13:02:23.337368,Bitstamp,https://www.bitstamp.net
3,Bitcoin Cash,bitcoin-cash,BCH,4,278.92,3.205290e-02,1.759249e+09,5051906817,18112350,18112350,2.100000e+07,0.17,-3.00,-4.76,3,2019-11-14 13:02:23.348683,Binance,https://www.binance.com/
4,Tether,tether,USDT,5,1.01,1.159000e-04,2.172326e+10,4141681919,4108044456,4207771504,NaN,-0.23,0.33,0.45,1,2019-11-14 13:02:23.360212,Bitstamp,https://www.bitstamp.net
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,iExec RLC,rlc,RLC,96,0.73,8.420000e-05,9.123598e+05,58690317,80070793,86999785,NaN,1.75,-2.65,10.64,1,2019-11-14 13:02:26.339720,Bitstamp,https://www.bitstamp.net
96,BitMax Token,bitmax-token,BTMX,97,0.07,8.000000e-06,3.352881e+06,54953077,787683608,787683608,NaN,-0.72,0.83,1.18,4,2019-11-14 13:02:26.349654,OKEx,https://www.okex.com
97,Flexacoin,flexacoin,FXC,98,0.00,3.000000e-07,2.182664e+04,54053204,21223945749,21223945749,1.000000e+11,0.01,2.53,-0.39,1,2019-11-14 13:02:26.359969,Bitstamp,https://www.bitstamp.net
98,Chiliz,chiliz,CHZ,99,0.01,1.600000e-06,1.139611e+07,53955717,3762769182,8888888888,NaN,0.84,-3.41,5.44,2,2019-11-14 13:02:26.376334,Poloniex,https://poloniex.com
99,Ardor,ardor,ARDR,100,0.05,6.100000e-06,2.348666e+06,53205799,998999495,998999495,9.989995e+08,-0.34,-4.22,-3.56,1,2019-11-14 13:02:26.387078,Bitstamp,https://www.bitstamp.net

In [39]:
crypto_df = combined_df.loc[:: , ('symbol' , 'price_usd' , 'percent_change_7d')]
crypto_df

   symbol  price_usd  percent_change_7d
0     BTC    8707.37              -5.91
1     ETH     186.50              -0.66
2     XRP       0.27              -8.22
3     BCH     278.92              -4.76
4    USDT       1.01               0.45
..    ...        ...                ...
95    RLC       0.73              10.64
96   BTMX       0.07               1.18
97    FXC       0.00              -0.39
98    CHZ       0.01               5.44
99   ARDR       0.05              -3.56

[100 rows x 3 columns]

In [47]:
# Once you have the crypto_df DataFrame, create a new weekly_change_df with the crypto_df data sorted by percent_change_7d from highest to lowest.

weekly_change_df = crypto_df.sort_values(by='percent_change_7d', ascending=False)
weekly_change_df

   symbol  price_usd  percent_change_7d
65     DX       0.00              89.14
39    MIN       1.36              72.90
74  SEELE       0.11              39.59
61    KMD       0.86              22.75
26    VET       0.01              21.49
..    ...        ...                ...
35    INB       0.64             -13.37
57    BTM       0.11             -13.42
64    SLV       0.95             -13.84
63    EKT       0.10             -14.31
59   LUNA       0.37             -17.84

[100 rows x 3 columns]