In [10]:
import pandas as pd
import lxml
import numpy as np
import requests

In [11]:
# Get FIFA players from the web
# Your task:

# Read and store in a fifa_df DataFrame the HTML table found in the fifa_players.html file that contains the top 30 FIFA players as of Oct. 30, 2019. The fifa_players.html file is a dump generated from this URL: https://www.fifaindex.com/players/top/fifa20_363/
# Remove the first two columns and the last one from the resulting fifa_df DataFrame, as they are Unnamed and filled with NaN objects.
# Create a most_hits_player variable containing the player with the most amount of Hits.

In [12]:
# W eneed to read our web file

dfs = pd.read_html(r'C:\Users\HP\Desktop\Data-Science-Foundations\web\fifa_players.html' , encoding= 'utf-8')
dfs

[    Unnamed: 0  Unnamed: 1  OVR-POT                        Name  \
 0          NaN         NaN     7587        Erling Braut  Håland
 1          NaN         NaN     9393           Cristiano Ronaldo
 2          NaN         NaN     9494                Lionel Messi
 3          NaN         NaN     8995               Kylian Mbappé
 4          NaN         NaN     8492                Jadon Sancho
 5          NaN         NaN     9292                   Neymar Jr
 6          NaN         NaN     8692             Frenkie de Jong
 7          NaN         NaN     8892                Paulo Dybala
 8          NaN         NaN     8187           Donny van de Beek
 9          NaN         NaN     7685               Tammy Abraham
 10         NaN         NaN     9191                 Eden Hazard
 11         NaN         NaN     9090               Mohamed Salah
 12         NaN         NaN     8788               Heung Min Son
 13         NaN         NaN     8585         Zlatan  Ibrahimović
 14         NaN         NaN     7484                Daniel James
 15         NaN         NaN     8389     Trent  Alexander-Arnold
 16         NaN         NaN     8389             Marcus Rashford
 17         NaN         NaN     8989           Antoine Griezmann
 18         NaN         NaN     8093                  João Félix
 19         NaN         NaN     8686                   CoutinhoL
 20         NaN         NaN     9191             Kevin De Bruyne
 21         NaN         NaN     9091             Virgil van Dijk
 22         NaN         NaN     8790              Bernardo Silva
 23         NaN         NaN     8189            Lautaro Martínez
 24         NaN         NaN     7586                 Mason Mount
 25         NaN         NaN     7689                     Rodrygo
 26         NaN         NaN     8989                 Luis Suárez
 27         NaN         NaN     8991                  Harry Kane
 28         NaN         NaN     8888  Pierre-Emerick  Aubameyang
 29         NaN         NaN     7187              Takefusa KuboL

    Preferred Positions  Age  Hits  Unnamed: 7
 0                   ST   19   245         NaN
 1                 STLW   34   185         NaN
 2               RWCFST   32   178         NaN
 3                 STRW   20   137         NaN
 4                 RMLM   19   125         NaN
 5                LWCAM   27   118         NaN
 6                CMCDM   22    93         NaN
 7                CAMRW   25    91         NaN
 8                CAMCM   22    90         NaN
 9                   ST   22    85         NaN
 10                LWCF   28    84         NaN
 11                RWST   27    83         NaN
 12                CFLM   27    80         NaN
 13                  ST   38    80         NaN
 14              LMLWRM   21    79         NaN
 15                  RB   21    77         NaN
 16                STLM   21    76         NaN
 17              CFSTLW   28    74         NaN
 18                CFST   19    74         NaN
 19               LWCAM   27    73         NaN
 20               CAMCM   28    73         NaN
 21                  CB   28    72         NaN
 22             RWCAMCM   25    72         NaN
 23                  ST   22    67         NaN
 24             CAMLWCM   20    66         NaN
 25              LWRWST   18    65         NaN
 26                  ST   32    63         NaN
 27                  ST   26    62         NaN
 28                STLM   30    62         NaN
 29                RMCF   18    61         NaN  ]

In [21]:
new_fifa_df = dfs[0]
new_fifa_df

,Unnamed: 0,Unnamed: 1,OVR-POT,Name,Preferred Positions,Age,Hits,Unnamed: 7
0,NaN,NaN,7587,Erling Braut Håland,ST,19,245,NaN
1,NaN,NaN,9393,Cristiano Ronaldo,STLW,34,185,NaN
2,NaN,NaN,9494,Lionel Messi,RWCFST,32,178,NaN
3,NaN,NaN,8995,Kylian Mbappé,STRW,20,137,NaN
4,NaN,NaN,8492,Jadon Sancho,RMLM,19,125,NaN
5,NaN,NaN,9292,Neymar Jr,LWCAM,27,118,NaN
6,NaN,NaN,8692,Frenkie de Jong,CMCDM,22,93,NaN
7,NaN,NaN,8892,Paulo Dybala,CAMRW,25,91,NaN
8,NaN,NaN,8187,Donny van de Beek,CAMCM,22,90,NaN
9,NaN,NaN,7685,Tammy Abraham,ST,22,85,NaN
10,NaN,NaN,9191,Eden Hazard,LWCF,28,84,NaN
11,NaN,NaN,9090,Mohamed Salah,RWST,27,83,NaN
12,NaN,NaN,8788,Heung Min Son,CFLM,27,80,NaN
13,NaN,NaN,8585,Zlatan Ibrahimović,ST,38,80,NaN
14,NaN,NaN,7484,Daniel James,LMLWRM,21,79,NaN
15,NaN,NaN,8389,Trent Alexander-Arnold,RB,21,77,NaN
16,NaN,NaN,8389,Marcus Rashford,STLM,21,76,NaN
17,NaN,NaN,8989,Antoine Griezmann,CFSTLW,28,74,NaN
18,NaN,NaN,8093,João Félix,CFST,19,74,NaN
19,NaN,NaN,8686,CoutinhoL,LWCAM,27,73,NaN
20,NaN,NaN,9191,Kevin De Bruyne,CAMCM,28,73,NaN
21,NaN,NaN,9091,Virgil van Dijk,CB,28,72,NaN
22,NaN,NaN,8790,Bernardo Silva,RWCAMCM,25,72,NaN
23,NaN,NaN,8189,Lautaro Martínez,ST,22,67,NaN
24,NaN,NaN,7586,Mason Mount,CAMLWCM,20,66,NaN
25,NaN,NaN,7689,Rodrygo,LWRWST,18,65,NaN
26,NaN,NaN,8989,Luis Suárez,ST,32,63,NaN
27,NaN,NaN,8991,Harry Kane,ST,26,62,NaN
28,NaN,NaN,8888,Pierre-Emerick Aubameyang,STLM,30,62,NaN
29,NaN,NaN,7187,Takefusa KuboL,RMCF,18,61,NaN

In [22]:
# Remove the 1st 2 columns and the last column

new_fifa_df = new_fifa_df.drop(columns = (['Unnamed: 0' , 'Unnamed: 1' , 'Unnamed: 7']))

In [23]:
new_fifa_df

    OVR-POT                        Name Preferred Positions  Age  Hits
0      7587        Erling Braut  Håland                  ST   19   245
1      9393           Cristiano Ronaldo                STLW   34   185
2      9494                Lionel Messi              RWCFST   32   178
3      8995               Kylian Mbappé                STRW   20   137
4      8492                Jadon Sancho                RMLM   19   125
5      9292                   Neymar Jr               LWCAM   27   118
6      8692             Frenkie de Jong               CMCDM   22    93
7      8892                Paulo Dybala               CAMRW   25    91
8      8187           Donny van de Beek               CAMCM   22    90
9      7685               Tammy Abraham                  ST   22    85
10     9191                 Eden Hazard                LWCF   28    84
11     9090               Mohamed Salah                RWST   27    83
12     8788               Heung Min Son                CFLM   27    80
13     8585         Zlatan  Ibrahimović                  ST   38    80
14     7484                Daniel James              LMLWRM   21    79
15     8389     Trent  Alexander-Arnold                  RB   21    77
16     8389             Marcus Rashford                STLM   21    76
17     8989           Antoine Griezmann              CFSTLW   28    74
18     8093                  João Félix                CFST   19    74
19     8686                   CoutinhoL               LWCAM   27    73
20     9191             Kevin De Bruyne               CAMCM   28    73
21     9091             Virgil van Dijk                  CB   28    72
22     8790              Bernardo Silva             RWCAMCM   25    72
23     8189            Lautaro Martínez                  ST   22    67
24     7586                 Mason Mount             CAMLWCM   20    66
25     7689                     Rodrygo              LWRWST   18    65
26     8989                 Luis Suárez                  ST   32    63
27     8991                  Harry Kane                  ST   26    62
28     8888  Pierre-Emerick  Aubameyang                STLM   30    62
29     7187              Takefusa KuboL                RMCF   18    61

In [28]:
# Create a most_hits_player variable containing the player with the most amount of Hits.

most_hits_player = new_fifa_df.sort_values(by= 'Hits' , ascending = False).value_counts()
most_hits_player.head(1)

OVR-POT  Name            Preferred Positions  Age  Hits
7187     Takefusa KuboL  RMCF                 18   61      1
Name: count, dtype: int64