In [1]:
import pandas as pd

In [2]:
# We have been reading data from csv files


# We see where else we can read the data

In [3]:
# # Excel files(The parameters are the same as those as those of csv)


# filepath: Path of the file to be read.

# sheet_name: Strings are used for sheet names. Integers are used in zero-indexed sheet positions. Lists of strings/integers are used to request multiple sheets. Specify None to get all sheets.

# header: Index of the row containing the names of the columns (None if none).

# index_col: Index of the column or sequence of indexes that should be used as index of rows of the data.

# names: Sequence containing the names of the columns (used together with header = None).

# skiprows: Number of rows or sequence of row indexes to ignore in the load.

# na_values: Sequence of values that, if found in the file, should be treated as NaN.

# dtype: Dictionary in which the keys will be column names and the values will be types of NumPy to which their content must be converted.

# parse_dates: Flag that indicates if Python should try to parse data with a format similar to dates as dates. You can enter a list of column names that must be joined for the parsing as a date.

# date_parser: Function to use to try to parse dates.

# nrows: Number of rows to read from the beginning of the file.

# skip_footer: Number of rows to ignore at the end of the file.

# squeeze: Flag that indicates that if the data read only contains one column the result is a Series instead of a DataFrame.

# thousands: Character to use to detect the thousands separator.

In [4]:
# Reading JSON FILES

In [7]:
# We try and reading the games.json

games = pd.read_json(r"C:\Users\HP\Desktop\Data-Science-Foundations\Json\games.json")
games.head()

,title,price,content_rating_img,release_date,provider,genre,image
0,Call of Duty®: WWII + Destiny 2 - Lote,"129,99 €",https://cdn-a.sonyentertainmentnetwork.com/grc...,Dic 21 2018,Activision Blizzard Int'l BV,Shooter,https://store.playstation.com/store/api/chihir...
1,God of War® Digital Deluxe Edition,"69,99 €",https://cdn-a.sonyentertainmentnetwork.com/grc...,Abr 20 2018,Sony Interactive Entertainment Europe,Acción,https://store.playstation.com/store/api/chihir...
2,Far Cry 5,"69,99 €",https://cdn-a.sonyentertainmentnetwork.com/grc...,Mar 27 2018,UBISOFT ENTERTAINMENT SA,Aventura,https://store.playstation.com/store/api/chihir...
3,Far Cry 5 Edición Deluxe,"79,99 €",https://cdn-a.sonyentertainmentnetwork.com/grc...,Mar 27 2018,UBISOFT ENTERTAINMENT SA,Aventura,https://store.playstation.com/store/api/chihir...
4,Far Cry 5 Edición Oro,"89,99 €",https://cdn-a.sonyentertainmentnetwork.com/grc...,Mar 27 2018,UBISOFT ENTERTAINMENT SA,Aventura,https://store.playstation.com/store/api/chihir...

In [ ]:
# The games.json is in a nice format. But sometimes the json file may be nested and the read_json will not work

In [8]:
# We try reading the nested file(users.json) where the read.json will not work we have to go an extra mile.

df = pd.read_json(r"C:\Users\HP\Desktop\Data-Science-Foundations\Json\users.json")
df.head()

                                                info
0  {'id': 1, 'name': 'Leanne Graham', 'username':...
1  {'id': 2, 'name': 'Ervin Howell', 'username': ...
2  {'id': 3, 'name': 'Clementine Bauch', 'usernam...
3  {'id': 4, 'name': 'Patricia Lebsack', 'usernam...
4  {'id': 5, 'name': 'Chelsey Dietrich', 'usernam...

In [ ]:
# When we look at the df above. read_json method is not the best method.

# We'll need to use the json Python module to parse our JSON file into a Python Dictionary object, to be able to index that dictionary and select nested data we want.

# To do that we'll use the json.load() method, that will parse our JSON file into a Python Dictionary json_dict.

In [9]:
import json

with open(r"C:\Users\HP\Desktop\Data-Science-Foundations\Json\users.json") as file:
    json_dict = json.load(file)

In [10]:
json_dict

{'info': [{'id': 1,
   'name': 'Leanne Graham',
   'username': 'Bret',
   'email': 'Sincere@april.biz',
   'address': [{'street': 'Kulas Light',
     'suite': 'Apt. 556',
     'city': 'Gwenborough',
     'zipcode': '92998-3874',
     'geo': {'lat': '-37.3159', 'lng': '81.1496'}}],
   'phone': '1-770-736-8031 x56442',
   'website': 'hildegard.org',
   'company': {'name': 'Romaguera-Crona',
    'catchPhrase': 'Multi-layered client-server neural-net',
    'bs': 'harness real-time e-markets'}},
  {'id': 2,
   'name': 'Ervin Howell',
   'username': 'Antonette',
   'email': 'Shanna@melissa.tv',
   'address': [{'street': 'Victor Plains',
     'suite': 'Suite 879',
     'city': 'Wisokyburgh',
     'zipcode': '90566-7771',
     'geo': {'lat': '-43.9509', 'lng': '-34.4618'}}],
   'phone': '010-692-6593 x09125',
   'website': 'anastasia.net',
   'company': {'name': 'Deckow-Crist',
    'catchPhrase': 'Proactive didactic contingency',
    'bs': 'synergize scalable supply-chains'}},
  {'id': 3,
   'name': 'Clementine Bauch',
   'username': 'Samantha',
   'email': 'Nathan@yesenia.net',
   'address': [{'street': 'Douglas Extension',
     'suite': 'Suite 847',
     'city': 'McKenziehaven',
     'zipcode': '59590-4157',
     'geo': {'lat': '-68.6102', 'lng': '-47.0653'}}],
   'phone': '1-463-123-4447',
   'website': 'ramiro.info',
   'company': {'name': 'Romaguera-Jacobson',
    'catchPhrase': 'Face to face bifurcated interface',
    'bs': 'e-enable strategic applications'}},
  {'id': 4,
   'name': 'Patricia Lebsack',
   'username': 'Karianne',
   'email': 'Julianne.OConner@kory.org',
   'address': [{'street': 'Hoeger Mall',
     'suite': 'Apt. 692',
     'city': 'South Elvis',
     'zipcode': '53919-4257',
     'geo': {'lat': '29.4572', 'lng': '-164.2990'}}],
   'phone': '493-170-9623 x156',
   'website': 'kale.biz',
   'company': {'name': 'Robel-Corkery',
    'catchPhrase': 'Multi-tiered zero tolerance productivity',
    'bs': 'transition cutting-edge web services'}},
  {'id': 5,
   'name': 'Chelsey Dietrich',
   'username': 'Kamren',
   'email': 'Lucio_Hettinger@annie.ca',
   'address': [{'street': 'Skiles Walks',
     'suite': 'Suite 351',
     'city': 'Roscoeview',
     'zipcode': '33263',
     'geo': {'lat': '-31.8129', 'lng': '62.5342'}}],
   'phone': '(254)954-1289',
   'website': 'demarco.info',
   'company': {'name': 'Keebler LLC',
    'catchPhrase': 'User-centric fault-tolerant solution',
    'bs': 'revolutionize end-to-end systems'}},
  {'id': 6,
   'name': 'Mrs. Dennis Schulist',
   'username': 'Leopoldo_Corkery',
   'email': 'Karley_Dach@jasper.info',
   'address': [{'street': 'Norberto Crossing',
     'suite': 'Apt. 950',
     'city': 'South Christy',
     'zipcode': '23505-1337',
     'geo': {'lat': '-71.4197', 'lng': '71.7478'}}],
   'phone': '1-477-935-8478 x6430',
   'website': 'ola.org',
   'company': {'name': 'Considine-Lockman',
    'catchPhrase': 'Synchronised bottom-line interface',
    'bs': 'e-enable innovative applications'}},
  {'id': 7,
   'name': 'Kurtis Weissnat',
   'username': 'Elwyn.Skiles',
   'email': 'Telly.Hoeger@billy.biz',
   'address': [{'street': 'Rex Trail',
     'suite': 'Suite 280',
     'city': 'Howemouth',
     'zipcode': '58804-1099',
     'geo': {'lat': '24.8918', 'lng': '21.8984'}}],
   'phone': '210.067.6132',
   'website': 'elvis.io',
   'company': {'name': 'Johns Group',
    'catchPhrase': 'Configurable multimedia task-force',
    'bs': 'generate enterprise e-tailers'}},
  {'id': 8,
   'name': 'Nicholas Runolfsdottir V',
   'username': 'Maxime_Nienow',
   'email': 'Sherwood@rosamond.me',
   'address': [{'street': 'Ellsworth Summit',
     'suite': 'Suite 729',
     'city': 'Aliyaview',
     'zipcode': '45169',
     'geo': {'lat': '-14.3990', 'lng': '-120.7677'}}],
   'phone': '586.493.6943 x140',
   'website': 'jacynthe.com',
   'company': {'name': 'Abernathy Group',
    'catchPhrase': 'Implemented secondary concept',
    'bs': 'e-enable extensible e-tailers'}},
  {'id': 9,
   'name': 'Glenna Reichert',
   'username': 'Delphine',
   'email': 'Chaim_McDermott@dana.io',
   'address': [{'street': 'Dayna Park',
     'suite': 'Suite 449',
     'city': 'Bartholomebury',
     'zipcode': '76495-3109',
     'geo': {'lat': '24.6463', 'lng': '-168.8889'}}],
   'phone': '(775)976-6794 x41206',
   'website': 'conrad.com',
   'company': {'name': 'Yost and Sons',
    'catchPhrase': 'Switchable contextually-based project',
    'bs': 'aggregate real-time technologies'}},
  {'id': 10,
   'name': 'Clementina DuBuque',
   'username': 'Moriah.Stanton',
   'email': 'Rey.Padberg@karina.biz',
   'address': [{'street': 'Kattie Turnpike',
     'suite': 'Suite 198',
     'city': 'Lebsackbury',
     'zipcode': '31428-2261',
     'geo': {'lat': '-38.2386', 'lng': '57.2232'}}],
   'phone': '024-648-3804',
   'website': 'ambrose.net',
   'company': {'name': 'Hoeger LLC',
    'catchPhrase': 'Centralized empowering task-force',
    'bs': 'target end-to-end models'}}]}

In [11]:
json_dict.keys()

dict_keys(['info'])

In [13]:
json_dict.values()

dict_values([[{'id': 1, 'name': 'Leanne Graham', 'username': 'Bret', 'email': 'Sincere@april.biz', 'address': [{'street': 'Kulas Light', 'suite': 'Apt. 556', 'city': 'Gwenborough', 'zipcode': '92998-3874', 'geo': {'lat': '-37.3159', 'lng': '81.1496'}}], 'phone': '1-770-736-8031 x56442', 'website': 'hildegard.org', 'company': {'name': 'Romaguera-Crona', 'catchPhrase': 'Multi-layered client-server neural-net', 'bs': 'harness real-time e-markets'}}, {'id': 2, 'name': 'Ervin Howell', 'username': 'Antonette', 'email': 'Shanna@melissa.tv', 'address': [{'street': 'Victor Plains', 'suite': 'Suite 879', 'city': 'Wisokyburgh', 'zipcode': '90566-7771', 'geo': {'lat': '-43.9509', 'lng': '-34.4618'}}], 'phone': '010-692-6593 x09125', 'website': 'anastasia.net', 'company': {'name': 'Deckow-Crist', 'catchPhrase': 'Proactive didactic contingency', 'bs': 'synergize scalable supply-chains'}}, {'id': 3, 'name': 'Clementine Bauch', 'username': 'Samantha', 'email': 'Nathan@yesenia.net', 'address': [{'street': 'Douglas Extension', 'suite': 'Suite 847', 'city': 'McKenziehaven', 'zipcode': '59590-4157', 'geo': {'lat': '-68.6102', 'lng': '-47.0653'}}], 'phone': '1-463-123-4447', 'website': 'ramiro.info', 'company': {'name': 'Romaguera-Jacobson', 'catchPhrase': 'Face to face bifurcated interface', 'bs': 'e-enable strategic applications'}}, {'id': 4, 'name': 'Patricia Lebsack', 'username': 'Karianne', 'email': 'Julianne.OConner@kory.org', 'address': [{'street': 'Hoeger Mall', 'suite': 'Apt. 692', 'city': 'South Elvis', 'zipcode': '53919-4257', 'geo': {'lat': '29.4572', 'lng': '-164.2990'}}], 'phone': '493-170-9623 x156', 'website': 'kale.biz', 'company': {'name': 'Robel-Corkery', 'catchPhrase': 'Multi-tiered zero tolerance productivity', 'bs': 'transition cutting-edge web services'}}, {'id': 5, 'name': 'Chelsey Dietrich', 'username': 'Kamren', 'email': 'Lucio_Hettinger@annie.ca', 'address': [{'street': 'Skiles Walks', 'suite': 'Suite 351', 'city': 'Roscoeview', 'zipcode': '33263', 'geo': {'lat': '-31.8129', 'lng': '62.5342'}}], 'phone': '(254)954-1289', 'website': 'demarco.info', 'company': {'name': 'Keebler LLC', 'catchPhrase': 'User-centric fault-tolerant solution', 'bs': 'revolutionize end-to-end systems'}}, {'id': 6, 'name': 'Mrs. Dennis Schulist', 'username': 'Leopoldo_Corkery', 'email': 'Karley_Dach@jasper.info', 'address': [{'street': 'Norberto Crossing', 'suite': 'Apt. 950', 'city': 'South Christy', 'zipcode': '23505-1337', 'geo': {'lat': '-71.4197', 'lng': '71.7478'}}], 'phone': '1-477-935-8478 x6430', 'website': 'ola.org', 'company': {'name': 'Considine-Lockman', 'catchPhrase': 'Synchronised bottom-line interface', 'bs': 'e-enable innovative applications'}}, {'id': 7, 'name': 'Kurtis Weissnat', 'username': 'Elwyn.Skiles', 'email': 'Telly.Hoeger@billy.biz', 'address': [{'street': 'Rex Trail', 'suite': 'Suite 280', 'city': 'Howemouth', 'zipcode': '58804-1099', 'geo': {'lat': '24.8918', 'lng': '21.8984'}}], 'phone': '210.067.6132', 'website': 'elvis.io', 'company': {'name': 'Johns Group', 'catchPhrase': 'Configurable multimedia task-force', 'bs': 'generate enterprise e-tailers'}}, {'id': 8, 'name': 'Nicholas Runolfsdottir V', 'username': 'Maxime_Nienow', 'email': 'Sherwood@rosamond.me', 'address': [{'street': 'Ellsworth Summit', 'suite': 'Suite 729', 'city': 'Aliyaview', 'zipcode': '45169', 'geo': {'lat': '-14.3990', 'lng': '-120.7677'}}], 'phone': '586.493.6943 x140', 'website': 'jacynthe.com', 'company': {'name': 'Abernathy Group', 'catchPhrase': 'Implemented secondary concept', 'bs': 'e-enable extensible e-tailers'}}, {'id': 9, 'name': 'Glenna Reichert', 'username': 'Delphine', 'email': 'Chaim_McDermott@dana.io', 'address': [{'street': 'Dayna Park', 'suite': 'Suite 449', 'city': 'Bartholomebury', 'zipcode': '76495-3109', 'geo': {'lat': '24.6463', 'lng': '-168.8889'}}], 'phone': '(775)976-6794 x41206', 'website': 'conrad.com', 'company': {'name': 'Yost and Sons', 'catchPhrase': 'Switchable contextually-based project', 'bs': 'aggregate real-time technologies'}}, {'id': 10, 'name': 'Clementina DuBuque', 'username': 'Moriah.Stanton', 'email': 'Rey.Padberg@karina.biz', 'address': [{'street': 'Kattie Turnpike', 'suite': 'Suite 198', 'city': 'Lebsackbury', 'zipcode': '31428-2261', 'geo': {'lat': '-38.2386', 'lng': '57.2232'}}], 'phone': '024-648-3804', 'website': 'ambrose.net', 'company': {'name': 'Hoeger LLC', 'catchPhrase': 'Centralized empowering task-force', 'bs': 'target end-to-end models'}}]])

In [14]:
# We read each value from the info key.

for user in json_dict['info']:
    print(user)

{'id': 1, 'name': 'Leanne Graham', 'username': 'Bret', 'email': 'Sincere@april.biz', 'address': [{'street': 'Kulas Light', 'suite': 'Apt. 556', 'city': 'Gwenborough', 'zipcode': '92998-3874', 'geo': {'lat': '-37.3159', 'lng': '81.1496'}}], 'phone': '1-770-736-8031 x56442', 'website': 'hildegard.org', 'company': {'name': 'Romaguera-Crona', 'catchPhrase': 'Multi-layered client-server neural-net', 'bs': 'harness real-time e-markets'}}
{'id': 2, 'name': 'Ervin Howell', 'username': 'Antonette', 'email': 'Shanna@melissa.tv', 'address': [{'street': 'Victor Plains', 'suite': 'Suite 879', 'city': 'Wisokyburgh', 'zipcode': '90566-7771', 'geo': {'lat': '-43.9509', 'lng': '-34.4618'}}], 'phone': '010-692-6593 x09125', 'website': 'anastasia.net', 'company': {'name': 'Deckow-Crist', 'catchPhrase': 'Proactive didactic contingency', 'bs': 'synergize scalable supply-chains'}}
{'id': 3, 'name': 'Clementine Bauch', 'username': 'Samantha', 'email': 'Nathan@yesenia.net', 'address': [{'street': 'Douglas Extension', 'suite': 'Suite 847', 'city': 'McKenziehaven', 'zipcode': '59590-4157', 'geo': {'lat': '-68.6102', 'lng': '-47.0653'}}], 'phone': '1-463-123-4447', 'website': 'ramiro.info', 'company': {'name': 'Romaguera-Jacobson', 'catchPhrase': 'Face to face bifurcated interface', 'bs': 'e-enable strategic applications'}}
{'id': 4, 'name': 'Patricia Lebsack', 'username': 'Karianne', 'email': 'Julianne.OConner@kory.org', 'address': [{'street': 'Hoeger Mall', 'suite': 'Apt. 692', 'city': 'South Elvis', 'zipcode': '53919-4257', 'geo': {'lat': '29.4572', 'lng': '-164.2990'}}], 'phone': '493-170-9623 x156', 'website': 'kale.biz', 'company': {'name': 'Robel-Corkery', 'catchPhrase': 'Multi-tiered zero tolerance productivity', 'bs': 'transition cutting-edge web services'}}
{'id': 5, 'name': 'Chelsey Dietrich', 'username': 'Kamren', 'email': 'Lucio_Hettinger@annie.ca', 'address': [{'street': 'Skiles Walks', 'suite': 'Suite 351', 'city': 'Roscoeview', 'zipcode': '33263', 'geo': {'lat': '-31.8129', 'lng': '62.5342'}}], 'phone': '(254)954-1289', 'website': 'demarco.info', 'company': {'name': 'Keebler LLC', 'catchPhrase': 'User-centric fault-tolerant solution', 'bs': 'revolutionize end-to-end systems'}}
{'id': 6, 'name': 'Mrs. Dennis Schulist', 'username': 'Leopoldo_Corkery', 'email': 'Karley_Dach@jasper.info', 'address': [{'street': 'Norberto Crossing', 'suite': 'Apt. 950', 'city': 'South Christy', 'zipcode': '23505-1337', 'geo': {'lat': '-71.4197', 'lng': '71.7478'}}], 'phone': '1-477-935-8478 x6430', 'website': 'ola.org', 'company': {'name': 'Considine-Lockman', 'catchPhrase': 'Synchronised bottom-line interface', 'bs': 'e-enable innovative applications'}}
{'id': 7, 'name': 'Kurtis Weissnat', 'username': 'Elwyn.Skiles', 'email': 'Telly.Hoeger@billy.biz', 'address': [{'street': 'Rex Trail', 'suite': 'Suite 280', 'city': 'Howemouth', 'zipcode': '58804-1099', 'geo': {'lat': '24.8918', 'lng': '21.8984'}}], 'phone': '210.067.6132', 'website': 'elvis.io', 'company': {'name': 'Johns Group', 'catchPhrase': 'Configurable multimedia task-force', 'bs': 'generate enterprise e-tailers'}}
{'id': 8, 'name': 'Nicholas Runolfsdottir V', 'username': 'Maxime_Nienow', 'email': 'Sherwood@rosamond.me', 'address': [{'street': 'Ellsworth Summit', 'suite': 'Suite 729', 'city': 'Aliyaview', 'zipcode': '45169', 'geo': {'lat': '-14.3990', 'lng': '-120.7677'}}], 'phone': '586.493.6943 x140', 'website': 'jacynthe.com', 'company': {'name': 'Abernathy Group', 'catchPhrase': 'Implemented secondary concept', 'bs': 'e-enable extensible e-tailers'}}
{'id': 9, 'name': 'Glenna Reichert', 'username': 'Delphine', 'email': 'Chaim_McDermott@dana.io', 'address': [{'street': 'Dayna Park', 'suite': 'Suite 449', 'city': 'Bartholomebury', 'zipcode': '76495-3109', 'geo': {'lat': '24.6463', 'lng': '-168.8889'}}], 'phone': '(775)976-6794 x41206', 'website': 'conrad.com', 'company': {'name': 'Yost and Sons', 'catchPhrase': 'Switchable contextually-based project', 'bs': 'aggregate real-time technologies'}}
{'id': 10, 'name': 'Clementina DuBuque', 'username': 'Moriah.Stanton', 'email': 'Rey.Padberg@karina.biz', 'address': [{'street': 'Kattie Turnpike', 'suite': 'Suite 198', 'city': 'Lebsackbury', 'zipcode': '31428-2261', 'geo': {'lat': '-38.2386', 'lng': '57.2232'}}], 'phone': '024-648-3804', 'website': 'ambrose.net', 'company': {'name': 'Hoeger LLC', 'catchPhrase': 'Centralized empowering task-force', 'bs': 'target end-to-end models'}}

In [ ]:
# With our Python Dictionary ready, we'll introduce another useful pandas method: from_dict().

# This from_dict method will construct a new DataFrame from a dict of array-like or dicts.

In [15]:
pd.DataFrame.from_dict({'Fruits': ['Apple', 'Banana']})

   Fruits
0   Apple
1  Banana

In [16]:
# You see each dictionary is like a column.

# But we can change the orientation using orient attribute

pd.DataFrame.from_dict({'Fruits': ['Apple', 'Banana']} , orient= 'index')

            0       1
Fruits  Apple  Banana

In [17]:
# Now we do the same with our json dictionary

pd.DataFrame.from_dict(json_dict)

                                                info
0  {'id': 1, 'name': 'Leanne Graham', 'username':...
1  {'id': 2, 'name': 'Ervin Howell', 'username': ...
2  {'id': 3, 'name': 'Clementine Bauch', 'usernam...
3  {'id': 4, 'name': 'Patricia Lebsack', 'usernam...
4  {'id': 5, 'name': 'Chelsey Dietrich', 'usernam...
5  {'id': 6, 'name': 'Mrs. Dennis Schulist', 'use...
6  {'id': 7, 'name': 'Kurtis Weissnat', 'username...
7  {'id': 8, 'name': 'Nicholas Runolfsdottir V', ...
8  {'id': 9, 'name': 'Glenna Reichert', 'username...
9  {'id': 10, 'name': 'Clementina DuBuque', 'user...

In [18]:
# We pass each dictionary now which will be made as keys as the columns and values as the rows

df = pd.DataFrame.from_dict(json_dict['info'])
df

,id,name,username,email,address,phone,website,company
0,1,Leanne Graham,Bret,Sincere@april.biz,"[{'street': 'Kulas Light', 'suite': 'Apt. 556'...",1-770-736-8031 x56442,hildegard.org,"{'name': 'Romaguera-Crona', 'catchPhrase': 'Mu..."
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,"[{'street': 'Victor Plains', 'suite': 'Suite 8...",010-692-6593 x09125,anastasia.net,"{'name': 'Deckow-Crist', 'catchPhrase': 'Proac..."
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,"[{'street': 'Douglas Extension', 'suite': 'Sui...",1-463-123-4447,ramiro.info,"{'name': 'Romaguera-Jacobson', 'catchPhrase': ..."
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,"[{'street': 'Hoeger Mall', 'suite': 'Apt. 692'...",493-170-9623 x156,kale.biz,"{'name': 'Robel-Corkery', 'catchPhrase': 'Mult..."
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,"[{'street': 'Skiles Walks', 'suite': 'Suite 35...",(254)954-1289,demarco.info,"{'name': 'Keebler LLC', 'catchPhrase': 'User-c..."
5,6,Mrs. Dennis Schulist,Leopoldo_Corkery,Karley_Dach@jasper.info,"[{'street': 'Norberto Crossing', 'suite': 'Apt...",1-477-935-8478 x6430,ola.org,"{'name': 'Considine-Lockman', 'catchPhrase': '..."
6,7,Kurtis Weissnat,Elwyn.Skiles,Telly.Hoeger@billy.biz,"[{'street': 'Rex Trail', 'suite': 'Suite 280',...",210.067.6132,elvis.io,"{'name': 'Johns Group', 'catchPhrase': 'Config..."
7,8,Nicholas Runolfsdottir V,Maxime_Nienow,Sherwood@rosamond.me,"[{'street': 'Ellsworth Summit', 'suite': 'Suit...",586.493.6943 x140,jacynthe.com,"{'name': 'Abernathy Group', 'catchPhrase': 'Im..."
8,9,Glenna Reichert,Delphine,Chaim_McDermott@dana.io,"[{'street': 'Dayna Park', 'suite': 'Suite 449'...",(775)976-6794 x41206,conrad.com,"{'name': 'Yost and Sons', 'catchPhrase': 'Swit..."
9,10,Clementina DuBuque,Moriah.Stanton,Rey.Padberg@karina.biz,"[{'street': 'Kattie Turnpike', 'suite': 'Suite...",024-648-3804,ambrose.net,"{'name': 'Hoeger LLC', 'catchPhrase': 'Central..."

In [ ]:
# In our example we still have two more complex columns, address and company.

# address: list of dictionaries (records)
# company: dictionary (record)
# The json_normalize method will be useful to unpack and flatten that data easily.

In [23]:

users = pd.json_normalize(json_dict)
users

                                                info
0  [{'id': 1, 'name': 'Leanne Graham', 'username'...

In [25]:
users = pd.json_normalize(json_dict['info'])
users.head()

,id,name,username,email,address,phone,website,company.name,company.catchPhrase,company.bs
0,1,Leanne Graham,Bret,Sincere@april.biz,"[{'street': 'Kulas Light', 'suite': 'Apt. 556'...",1-770-736-8031 x56442,hildegard.org,Romaguera-Crona,Multi-layered client-server neural-net,harness real-time e-markets
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,"[{'street': 'Victor Plains', 'suite': 'Suite 8...",010-692-6593 x09125,anastasia.net,Deckow-Crist,Proactive didactic contingency,synergize scalable supply-chains
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,"[{'street': 'Douglas Extension', 'suite': 'Sui...",1-463-123-4447,ramiro.info,Romaguera-Jacobson,Face to face bifurcated interface,e-enable strategic applications
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,"[{'street': 'Hoeger Mall', 'suite': 'Apt. 692'...",493-170-9623 x156,kale.biz,Robel-Corkery,Multi-tiered zero tolerance productivity,transition cutting-edge web services
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,"[{'street': 'Skiles Walks', 'suite': 'Suite 35...",(254)954-1289,demarco.info,Keebler LLC,User-centric fault-tolerant solution,revolutionize end-to-end systems

In [ ]:
# Company column further split into 3 other columns: company.name, company.catchPhrase and company.bs.

In [ ]:
# Unpack column with a list of records
# When we have a column with a list of nested values (records, dictionary) it's difficult to deal with it.

# json_normalize let us define a record_path parameter to define the path to a column with a list of records to unpack them. If this parameter is not passed, data will be assumed to be an array of records.

# In our case we'll unpack the address column into a standalone DataFrame.

In [26]:
address = pd.json_normalize(json_dict['info'] , sep= '_' , record_path= 'address')

In [27]:
address.head()

,street,suite,city,zipcode,geo_lat,geo_lng
0,Kulas Light,Apt. 556,Gwenborough,92998-3874,-37.3159,81.1496
1,Victor Plains,Suite 879,Wisokyburgh,90566-7771,-43.9509,-34.4618
2,Douglas Extension,Suite 847,McKenziehaven,59590-4157,-68.6102,-47.0653
3,Hoeger Mall,Apt. 692,South Elvis,53919-4257,29.4572,-164.2990
4,Skiles Walks,Suite 351,Roscoeview,33263,-31.8129,62.5342

In [31]:
artists_df = pd.read_json(r"C:\Users\HP\Desktop\Data-Science-Foundations\Json\artists.json")
artists_df.head(2)

,name,years,genre,nationality,bio
0,Amedeo Modigliani,1884 - 1920,Expressionism,Italian,"[{'full name': 'Amedeo Clemente Modigliani', '..."
1,Vasiliy Kandinskiy,1866 - 1944,"Expressionism,Abstractionism",Russian,[{'full name': 'Wassily Wassilyevich Kandinsky...

In [32]:
# Bio column is nested. So we have to pass it throught the normalize

with open (r'C:\Users\HP\Desktop\Data-Science-Foundations\Json\artists.json') as file:
    artists_dict = json.load(file)

In [35]:
artists_dict

[{'name': 'Amedeo Modigliani',
  'years': '1884 - 1920',
  'genre': 'Expressionism',
  'nationality': 'Italian',
  'bio': [{'full name': 'Amedeo Clemente Modigliani',
    'pronunciation': '[ameˈdɛːo modiʎˈʎaːni]',
    'life span': '12 July 1884 – 24 January 1920',
    'info': "was an Italian Jewish painter and sculptor who worked mainly in France. He is known for portraits and nudes in a modern style characterized by elongation of faces, necks, and figures that were not received well during his lifetime but later found acceptance. Modigliani spent his youth in Italy, where he studied the art of antiquity and the Renaissance. In 1906 he moved to Paris, where he came into contact with such artists as Pablo Picasso and Constantin Brâncuși. By 1912 Modigliani was exhibiting highly stylized sculptures with Cubists of the Section d'Or group at the Salon d'Automne.",
    'wikipedia': 'http://en.wikipedia.org/wiki/Amedeo_Modigliani',
    'paintings': 193}]},
 {'name': 'Vasiliy Kandinskiy',
  'years': '1866 - 1944',
  'genre': 'Expressionism,Abstractionism',
  'nationality': 'Russian',
  'bio': [{'full name': 'Wassily Wassilyevich Kandinsky',
    'pronunciation': 'Васи́лий Васи́льевич Канди́нский, tr. Vasíliy Vasílʹevich Kandínskiy',
    'life span': '16 December [O.S. 4 December] 1866 – 13 December 1944',
    'info': 'was a Russian painter and art theorist.',
    'wikipedia': 'http://en.wikipedia.org/wiki/Wassily_Kandinsky',
    'paintings': 88}]},
 {'name': 'Diego Rivera',
  'years': '1886 - 1957',
  'genre': 'Social Realism,Muralism',
  'nationality': 'Mexican',
  'bio': [{'full name': 'Diego María de la Concepción Juan Nepomuceno Estanislao de la Rivera y Barrientos Acosta y Rodríguez, known as Diego Rivera',
    'pronunciation': '[ˈdjeɣo riˈβeɾa]',
    'life span': 'December 8, 1886 – November 24, 1957',
    'info': 'was a prominent Mexican painter. His large frescoes helped establish the Mexican mural movement in Mexican art. Between 1922 and 1953, Rivera painted murals in, among other places, Mexico City, Chapingo, Cuernavaca, San Francisco, Detroit, and New York City. In 1931, a retrospective exhibition of his works was held at the Museum of Modern Art in New York. Rivera had a volatile marriage with fellow Mexican artist Frida Kahlo.',
    'wikipedia': 'http://en.wikipedia.org/wiki/Diego_Rivera',
    'paintings': 70}]},
 {'name': 'Claude Monet',
  'years': '1840 - 1926',
  'genre': 'Impressionism',
  'nationality': 'French',
  'bio': [{'full name': 'Oscar-Claude Monet',
    'pronunciation': '[klod mɔnɛ]',
    'life span': '14 November 1840 – 5 December 1926',
    'info': "was a French painter, a founder of French Impressionist painting and the most consistent and prolific practitioner of the movement's philosophy of expressing one's perceptions before nature, especially as applied to plein air landscape painting. The term 'Impressionism' is derived from the title of his painting Impression, soleil levant (Impression, Sunrise), which was exhibited in 1874 in the first of the independent exhibitions mounted by Monet and his associates as an alternative to the Salon de Paris.Monet's ambition of documenting the French countryside led him to adopt a method of painting the same scene many times in order to capture the changing of light and the passing of the seasons. From 1883, Monet lived in Giverny, where he purchased a house and property and began a vast landscaping project which included lily ponds that would become the subjects of his best-known works. In 1899, he began painting the water lilies, first in vertical views with a Japanese bridge as a central feature and later in the series of large-scale paintings that was to occupy him continuously for the next 20 years of his life.",
    'wikipedia': 'http://en.wikipedia.org/wiki/Claude_Monet',
    'paintings': 73}]},
 {'name': 'Rene Magritte',
  'years': '1898 - 1967',
  'genre': 'Surrealism,Impressionism',
  'nationality': 'Belgian',
  'bio': [{'full name': 'René François Ghislain Magritte',
    'pronunciation': '[ʁəne fʁɑ̃swa ɡilɛ̃ maɡʁit]',
    'life span': '21 November 1898 – 15 August 1967',
    'info': "Was a Belgian Surrealist artist. He became well known for creating a number of witty and thought-provoking images. Often depicting ordinary objects in an unusual context, his work is known for challenging observers' preconditioned perceptions of reality. His imagery has influenced Pop art, minimalist and conceptual art.",
    'wikipedia': 'http://en.wikipedia.org/wiki/René_Magritte',
    'paintings': 194}]}]

In [39]:
# Look above we notice that we have a list that has dictionaries. We use the normalize method

new_artist_dict = pd.json_normalize(artists_dict , record_path= 'bio')

In [40]:
new_artist_dict.head(1)

,full name,pronunciation,life span,info,wikipedia,paintings
0,Amedeo Clemente Modigliani,[ameˈdɛːo modiʎˈʎaːni],12 July 1884 – 24 January 1920,was an Italian Jewish painter and sculptor who...,http://en.wikipedia.org/wiki/Amedeo_Modigliani,193